title: Tommy's Website
description: >- # this means to ignore newlines until "baseurl:"
  Hello, I'm Tommy, a recent Computer Science graduate from the University of Alberta. I have a strong interest in software systems I have experience in several languages and technologies, but mainly C, Rust, Linux. Aside from computer science, my interests include reading about philosophy 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tommy-sand

# Build settings
theme: no-style-please
plugins:
  - jekyll-feed

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: compressed

plugins:
  - jekyll-feed
